# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    goamd64:
      - v3
    ldflags:
      - -s -w
      - >-
        -X main.name={{ .ProjectName }}
        -X main.version={{ .Version }}
        -X main.date={{ .CommitDate }}
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    main: ./main.go

upx:
  - enabled: true
    goos: [linux, windows]
    compress: best
    lzma: true

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - src: README.md
        info:
          mtime: "{{ .CommitDate }}"
      - src: LICENSE.md
        info:
          mtime: "{{ .CommitDate }}"
    # wrap_in_directory: true

report_sizes: true

changelog:
  disable: true
